'use strict';
(()=>{
const $=id=>document.getElementById(id);const KEY='fafa_size_v2';const started=Date.now();
const initial={projects:[],tasks:[],risks:[],decisions:[],automations:[],files:[],activity:[],chat:[],profile:{name:'',role:''}};
let db;try{db={...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')};}catch{db=structuredClone(initial);}
const save=()=>{localStorage.setItem(KEY,JSON.stringify(db));renderAll();};
const clean=s=>String(s).replace(/[<>]/g,'').trim();const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
function log(action){db.activity.unshift({id:uid(),text:action,at:new Date().toISOString()});db.activity=db.activity.slice(0,100);}
function remove(kind,id){db[kind]=db[kind].filter(x=>x.id!==id);log('Item removido de '+kind);save();}
function toggleTask(id){const t=db.tasks.find(x=>x.id===id);if(t){t.done=!t.done;log((t.done?'Tarefa concluída: ':'Tarefa reaberta: ')+t.title);save();}}
function recordList(kind,target,extra){const box=$(target);box.replaceChildren();if(!db[kind].length){box.innerHTML='<p class="empty-state">Nenhum registro.</p>';return;}db[kind].forEach(item=>{const row=document.createElement('div');row.className='record'+(item.done?' done':'');const main=document.createElement('div');main.innerHTML=`<strong>${escapeHTML(item.title||item.name)}</strong><small>${escapeHTML(extra(item))}</small>`;row.append(main);if(kind==='tasks'){const done=document.createElement('button');done.className='icon-button';done.type='button';done.textContent=item.done?'↶':'✓';done.title=item.done?'Reabrir':'Concluir';done.onclick=()=>toggleTask(item.id);row.append(done);}const del=document.createElement('button');del.className='icon-button danger';del.type='button';del.textContent='×';del.title='Remover';del.onclick=()=>remove(kind,item.id);row.append(del);box.append(row);});}
function renderProjects(){const box=$('project-list');box.replaceChildren();if(!db.projects.length){box.innerHTML='<p class="empty-state">Crie o primeiro projeto para começar.</p>';}db.projects.forEach(p=>{const card=document.createElement('article');card.className='project-card';card.innerHTML=`<span class="status-badge">${escapeHTML(p.status)}</span><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.client||'Cliente não informado')}</p><small>Criado em ${new Date(p.at).toLocaleDateString('pt-BR')}</small>`;const del=document.createElement('button');del.type='button';del.className='icon-button danger';del.textContent='×';del.title='Remover projeto';del.onclick=()=>remove('projects',p.id);card.append(del);box.append(card);});}
function renderFiles(){const box=$('file-list');box.replaceChildren();if(!db.files.length){box.innerHTML='<p class="empty-state">Nenhum arquivo registrado.</p>';return;}db.files.forEach(f=>{const row=document.createElement('div');row.className='record';row.innerHTML=`<div><strong>${escapeHTML(f.name)}</strong><small>${escapeHTML(f.type||'Tipo desconhecido')} · ${(f.size/1024).toFixed(1)} KB</small></div>`;const del=document.createElement('button');del.type='button';del.className='icon-button danger';del.textContent='×';del.onclick=()=>remove('files',f.id);row.append(del);box.append(row);});}
function renderActivity(){const box=$('activity-list');box.replaceChildren();if(!db.activity.length){box.innerHTML='<p class="empty-state">As ações aparecerão aqui.</p>';return;}db.activity.slice(0,15).forEach(a=>{const item=document.createElement('div');item.className='activity';item.innerHTML=`<i></i><div><strong>${escapeHTML(a.text)}</strong><small>${new Date(a.at).toLocaleString('pt-BR')}</small></div>`;box.append(item);});}
function renderChat(){const box=$('chat-messages');box.querySelectorAll('.persisted').forEach(n=>n.remove());db.chat.slice(-20).forEach(m=>{const d=document.createElement('div');d.className='message persisted '+m.role;d.textContent=m.text;box.append(d);});box.scrollTop=box.scrollHeight;}
function renderGraph(){const svg=$('knowledge-graph');const projects=db.projects.slice(0,6);const nodes=[{x:380,y:210,label:'FAFA',r:44,c:'#00ab78'}, {x:175,y:90,label:'MONTANI',r:30,c:'#00b3b8'}, {x:585,y:90,label:'MASTPLAN',r:30,c:'#74c998'}, {x:380,y:355,label:'ENGENHARIA',r:30,c:'#0f7d5a'}];projects.forEach((p,i)=>nodes.push({x:95+i%3*285,y:250+Math.floor(i/3)*90,label:p.name.slice(0,14).toUpperCase(),r:20,c:'#95cdb5'}));let markup='<g stroke="#346457" stroke-width="1.5" opacity=".7">';nodes.slice(1).forEach(n=>markup+=`<line x1="380" y1="210" x2="${n.x}" y2="${n.y}"/>`);markup+='</g>';nodes.forEach(n=>markup+=`<g><circle cx="${n.x}" cy="${n.y}" r="${n.r}" fill="${n.c}22" stroke="${n.c}" stroke-width="2"/><text x="${n.x}" y="${n.y+4}" text-anchor="middle" fill="#eff5f1" font-size="${n.r>35?15:10}" font-family="Montserrat">${escapeHTML(n.label)}</text></g>`);svg.innerHTML=markup;}
function renderAll(){const openTasks=db.tasks.filter(t=>!t.done).length; $('metric-projects').textContent=db.projects.length;$('metric-tasks').textContent=openTasks;$('metric-risks').textContent=db.risks.length;$('metric-decisions').textContent=db.decisions.length;$('task-count').textContent=openTasks;$('risk-count').textContent=db.risks.length;$('decision-count').textContent=db.decisions.length;$('project-count').textContent=db.projects.length;recordList('tasks','task-list',x=>x.priority+' · '+(x.done?'Concluída':'Aberta'));recordList('risks','risk-list',x=>'Nível '+x.level);recordList('decisions','decision-list',x=>new Date(x.at).toLocaleDateString('pt-BR'));recordList('automations','automation-list',x=>new Date(x.time).toLocaleString('pt-BR'));renderProjects();renderFiles();renderActivity();renderChat();renderGraph();$('profile-name').value=db.profile.name||'';$('profile-role').value=db.profile.role||'';$('system-online').textContent=navigator.onLine?'ONLINE':'OFFLINE';$('storage-size').textContent=(new Blob([JSON.stringify(db)]).size/1024).toFixed(1)+' KB';}
function bindForm(id,handler){$(id).addEventListener('submit',e=>{e.preventDefault();handler(new FormData(e.currentTarget));e.currentTarget.reset();save();});}
bindForm('task-form',()=>{const title=clean($('task-title').value);db.tasks.unshift({id:uid(),title,priority:$('task-priority').value,done:false,at:new Date().toISOString()});log('Tarefa criada: '+title);});
bindForm('risk-form',()=>{const title=clean($('risk-title').value);db.risks.unshift({id:uid(),title,level:$('risk-level').value,at:new Date().toISOString()});log('Risco registrado: '+title);});
bindForm('decision-form',()=>{const title=clean($('decision-title').value);db.decisions.unshift({id:uid(),title,at:new Date().toISOString()});log('Decisão registrada: '+title);});
bindForm('automation-form',()=>{const title=clean($('automation-title').value);db.automations.unshift({id:uid(),title,time:$('automation-time').value,fired:false});log('Lembrete agendado: '+title);});
bindForm('project-form',()=>{const name=clean($('project-name').value);db.projects.unshift({id:uid(),name,client:clean($('project-client').value),status:$('project-status').value,at:new Date().toISOString()});log('Projeto criado: '+name);});
$('profile-form').addEventListener('submit',e=>{e.preventDefault();db.profile={name:clean($('profile-name').value),role:clean($('profile-role').value)};log('Perfil local atualizado');save();toast('Perfil salvo neste navegador.');});
$('file-input').addEventListener('change',e=>{[...e.target.files].forEach(f=>db.files.unshift({id:uid(),name:f.name,type:f.type,size:f.size,modified:f.lastModified}));log(e.target.files.length+' arquivo(s) registrado(s)');e.target.value='';save();});
$('clear-activity').onclick=()=>{db.activity=[];save();};
$('export-report').onclick=()=>{const summary={generatedAt:new Date().toISOString(),profile:db.profile,metrics:{projects:db.projects.length,openTasks:db.tasks.filter(t=>!t.done).length,risks:db.risks.length,decisions:db.decisions.length},projects:db.projects,tasks:db.tasks,risks:db.risks,decisions:db.decisions};const url=URL.createObjectURL(new Blob([JSON.stringify(summary,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='fafa-relatorio-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);log('Relatório exportado');save();};
function fafaReply(text){const r=recommend(text);if(r.library)return 'Esse pedido aponta para a Biblioteca. Abra a seção Biblioteca para consultar os materiais disponíveis.';if(r.ids?.length){const names=r.ids.map(id=>byId(id)?.name).filter(Boolean);return `Recomendo ${names.join(' → ')}. Preparei esse caminho na Visão geral.`;}return r.question||'Conte um pouco mais sobre o resultado desejado.';}
$('chat-form').addEventListener('submit',e=>{e.preventDefault();const text=clean($('chat-input').value);if(!text)return;db.chat.push({role:'user',text},{role:'assistant',text:fafaReply(text)});log('Conversa: '+text.slice(0,60));$('chat-input').value='';save();try{submitBrief(text);}catch{} });
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
function startVoice(target){if(!Recognition){$('voice-status').textContent='Reconhecimento de voz não disponível neste navegador.';return;}const rec=new Recognition();rec.lang='pt-BR';rec.interimResults=false;$('voice-status').textContent='Ouvindo…';rec.onresult=e=>{$(target).value=e.results[0][0].transcript;$('voice-status').textContent='Texto reconhecido.';};rec.onerror=()=>{$('voice-status').textContent='Não foi possível usar o microfone.';};rec.onend=()=>{if($('voice-status').textContent==='Ouvindo…')$('voice-status').textContent='Escuta encerrada.';};rec.start();}
$('voice-chat').onclick=()=>startVoice('chat-input');$('voice-project').onclick=()=>startVoice('project-name');
setInterval(()=>{const now=Date.now();let changed=false;db.automations.forEach(a=>{if(!a.fired&&new Date(a.time).getTime()<=now){a.fired=true;changed=true;toast('Lembrete: '+a.title);log('Lembrete executado: '+a.title);}});if(changed)save();$('session-time').textContent=new Date(Date.now()-started).toISOString().slice(11,19);},1000);
addEventListener('online',renderAll);addEventListener('offline',renderAll);renderAll();
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const register=tool=>Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});
 register({name:'create_local_project',title:'Criar projeto local',description:'Cria um projeto no painel local do Fafa. Não envia dados para serviços externos.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:2,maxLength:100},client:{type:'string',maxLength:100},status:{type:'string',enum:['Planejamento','Em andamento','Em revisão','Concluído']}},required:['name'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const name=clean(input.name);db.projects.unshift({id:uid(),name,client:clean(input.client||''),status:input.status||'Planejamento',at:new Date().toISOString()});log('Projeto criado: '+name);save();return {created:true,name,totalProjects:db.projects.length};}});
 register({name:'create_local_task',title:'Criar tarefa local',description:'Cria uma tarefa no painel local do Fafa.',inputSchema:{type:'object',properties:{title:{type:'string',minLength:2,maxLength:120},priority:{type:'string',enum:['Baixa','Normal','Alta']}},required:['title'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const title=clean(input.title);db.tasks.unshift({id:uid(),title,priority:input.priority||'Normal',done:false,at:new Date().toISOString()});log('Tarefa criada: '+title);save();return {created:true,title,openTasks:db.tasks.filter(t=>!t.done).length};}});
 register({name:'read_local_dashboard',title:'Consultar painel local',description:'Retorna somente os totais operacionais visíveis no painel.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return {projects:db.projects.length,openTasks:db.tasks.filter(t=>!t.done).length,risks:db.risks.length,decisions:db.decisions.length,agents:agents.length,driveIntegration:'pending'};}});
 addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
})();
